# Top level values for starburst-enterprise-platform
# Overwrite defaults with values specific to Google Cloud marketplace

deployerHelm:
  image: "gcr.io/starburst-public/starburstdata/deployer:2.3.0"

reportingSecret: ENTERPRISE_LICENSE_NAME

metricsReporter:
  image: "gcr.io/starburst-public/starburstdata/metrics_reporter:2.3.0"

imageUbbagent: "gcr.io/cloud-marketplace-tools/metering/ubbagent:latest"

starburst-enterprise:
  image:
    repository: "gcr.io/starburst-public/starburstdata"
    tag: 2.3.0
  initImage:
    repository: "gcr.io/starburst-public/starburstdata/starburst-enterprise-init"
    tag: 2.3.0
  prometheus:
    enabled: false
  catalogs:
    bigquery: |
      connector.name=bigquery
      bigquery.project-id=GOOGLE_PROJECT_ID
    hive: |
      connector.name=hive
      hive.allow-drop-table=true
      hive.metastore.uri=thrift://hive:9083
    starburst-insights: |
      connector.name=postgresql
      connection-url=jdbc:postgresql://postgresql:5432/insights
      connection-user=postgres
      connection-password=password123

  coordinator:
    additionalProperties: |
      insights.persistence-enabled=true
      insights.metrics-persistence-enabled=true
      insights.jdbc.url=jdbc:postgresql://postgresql:5432/insights
      insights.jdbc.user=postgres
      insights.jdbc.password=password123
      insights.authorized-users=.*
    etcFiles:
      properties:
        config.properties: |
          coordinator=true
          node-scheduler.include-coordinator=false
          http-server.http.port=8080
          usage-metrics.cluster-usage-resource.enabled=true
          http-server.authentication.allow-insecure-over-http=true
          web-ui.enabled=true
          http-server.process-forwarded=true
        event-listener.properties: |
          event-listener.name=event-logger
          jdbc.url=jdbc:postgresql://postgresql:5432/insights
          jdbc.user=postgres
          jdbc.password=password123
    nodeSelector:
      starburstpool: base
    resources:
      limits:
        cpu: 15
        memory: 56Gi
      requests:
        cpu: 15
        memory: 56Gi

  expose:
    type: clusterIp
    ingress:
      serviceName: starburst
      servicePort: 8080
      host: STARBURST_URL
      path: "/"
      pathType: Prefix
      tls:
        enabled: true
        secretName: tls-secret-starburst
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt

  starburstPlatformLicense: sep-license

  worker:
    autoscaling:
      enabled: true
      maxReplicas: 10
      minReplicas: 1
      targetCPUUtilizationPercentage: 80
    deploymentTerminationGracePeriodSeconds: 30
    etcFiles:
      properties:
        event-listener.properties: |
          event-listener.name=event-logger
          jdbc.url=jdbc:postgresql://postgresql:5432/insights
          jdbc.user=postgres
          jdbc.password=password123
    nodeSelector:
      starburstpool: worker
    resources:
      limits:
        cpu: 15
        memory: 56Gi
      requests:
        cpu: 15
        memory: 56Gi
    starburstWorkerShutdownGracePeriodSeconds: 120

# Hive Chart
starburst-hive:
  enabled: true

  image:
    repository: "gcr.io/starburst-public/starburstdata/hive"
    tag: 2.3.0

  gcpExtraNodePool: EXTRA_NODE_POOL

  database:
    external:
      driver: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://postgresql:5432/hive
      user: postgres
      password: password123
    type: external

  objectStorage:
    gs:
      cloudKeyFileSecret: service-account-key

  expose:
    type: clusterIp

# Ranger Chart
starburst-ranger:
  enabled: false
