apiVersion: cert-manager.io/v1

kind:   ClusterIssuer

metadata:
  name: acme

  namespace: certs-manager

spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: <your email goes here>
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class : nginx
          podTemplate:
            spec:
              nodeSelector:
                "starburstpool": base